### ISSUE TITLE
Unclear requirements to student import

### ISSUE THREAD

**Issue by Inf1n1te** [Inf1n1te/Seth#270]
Currently, when all the correct column headers are in the student import sheet, it sometimes does not work. with the error that either the correct headers are not there or the rows are empty. Current possible causes: either the other rows have to be deleted or the headers should not be bold. We should figure out what is the exact cause and either fix it or give more explaination.

**Comment by MartijnVerkleij** [comment]
The check_dimensions check was lazily written and should be split up into multiple checks, each throwing their own error.

**Comment by MartijnVerkleij** [comment]
The checks have not been split, but with canvas export this issue effectively disappears for the end user.
